const theme = {
  fontWeights: {
    thin: 100,
    extraLight: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
    firaCodeRegular: 400,
    interBold: 700,
    interMedium: 500,
    interRegular: 400,
    interSemiBold: 600,
  },
  fontSizes: [
    "0.75rem",
    "0.8125rem",
    "0.875rem",
    "1rem",
    "1.125rem",
    "1.25rem",
    "1.5rem",
    "2rem",
    "2.5rem",
  ],
  lineHeights: {
    appCaption: "18px",
    appBodyL: "20px",
    appBodyM: "20px",
    appBodyS: "20px",
    appCode: "20px",
    appSection: "20px",
    webCode: "20px",
    webSection: "20px",
    webBodySecondaryL: "26px",
    webBodySecondaryM: "26px",
    webBodySecondaryS: "26px",
    webBodyPrimaryL: "30px",
    webBodyPrimaryM: "30px",
    webBodyPrimaryS: "30px",
    appSubtitle: "32px",
    appTitle2: "32px",
    webSubtitle: "32px",
    webTitle2: "32px",
    appTitle1: "40px",
    webTitle1: "40px",
    webHeadline: "48px",
  },
  letterSpacings: { appSection: "0.06px", webSection: "0.06px" },
  colors: {
    backgroundButtonDestructiveActive: "#ff715c",
    backgroundButtonDestructiveDefault: "#f5483f",
    backgroundButtonDestructiveHover: "#db262c",
    backgroundButtonDestructiveTextHover: "#fee4e2",
    backgroundButtonPrimaryActive: "#8a78ee",
    backgroundButtonPrimaryDefault: "#624de3",
    backgroundButtonPrimaryHover: "#4938c3",
    backgroundButtonSecondaryActive: "#dee4ed",
    backgroundButtonSecondaryDefault: "#ffffff",
    backgroundButtonSecondaryHover: "#f6f8fb",
    backgroundButtonWarningActive: "#ffdfb8",
    backgroundButtonWarningDefault: "#fff4e6",
    backgroundComponentChild: "#f6f8fb",
    backgroundComponentDisabled: "#f6f8fb",
    backgroundComponentElevatedElement: "#ffffff",
    backgroundComponentError: "#fee4e2",
    backgroundComponentHighlight: "#e7e4fb",
    backgroundComponentHoverOnDarkest: "#dee4ed",
    backgroundComponentHoverOnLightest: "#f6f8fb",
    backgroundComponentInfo: "#dbecfe",
    backgroundComponentInput: "#ffffff",
    backgroundComponentParent: "#ffffff",
    backgroundComponentSuccess: "#e6f7e5",
    backgroundComponentTooltip: "#181e25",
    backgroundComponentWarning: "#fff4e6",
    backgroundSurfaceOverlay: "#181e25",
    backgroundSurfaceSurface1: "#ffffff",
    backgroundSurfaceSurface2: "#f6f8fb",
    backgroundSurfaceSurface3: "#dee4ed",
    borderButtonDestructiveDefault: "#db262c",
    borderButtonDestructiveFocused: "#fee4e2",
    borderButtonPrimaryDefault: "#4938c3",
    borderButtonPrimaryFocused: "#e7e4fb",
    borderButtonSecondaryDefault: "#dee4ed",
    borderButtonWarningHover: "#ffdfb8",
    borderComponentActive: "#624de3",
    borderComponentDarkestBorder: "#5c6f8a",
    borderComponentError: "#f5483f",
    borderComponentLightestBorder: "#dee4ed",
    globalAppVioletBase: "#624de3",
    globalAppVioletDark: "#4938c3",
    globalAppVioletLight: "#8a78ee",
    globalAppVioletLighter: "#e7e4fb",
    globalBlueBase: "#117df9",
    globalBlueLighter: "#dbecfe",
    globalGreenBase: "#58cd52",
    globalGreenLighter: "#e6f7e5",
    globalNeutral1: "#ffffff",
    globalNeutral2: "#f6f8fb",
    globalNeutral3: "#dee4ed",
    globalNeutral4: "#ccd5e1",
    globalNeutral5: "#b3c0d0",
    globalNeutral6: "#788ba5",
    globalNeutral7: "#5c6f8a",
    globalNeutral8: "#323b48",
    globalNeutral9: "#181e25",
    globalOrangeBase: "#ff8e05",
    globalOrangeLight: "#ffdfb8",
    globalOrangeLighter: "#fff4e6",
    globalRedBase: "#f5483f",
    globalRedDark: "#db262c",
    globalRedLight: "#ff715c",
    globalRedLighter: "#fee4e2",
    iconDefault: "#788ba5",
    iconDisabled: "#ccd5e1",
    iconError: "#f5483f",
    iconInfo: "#117df9",
    iconOnColoredBg: "#ffffff",
    iconSelected: "#624de3",
    iconSuccess: "#58cd52",
    iconWarning: "#ff8e05",
    skeletonDefault: "#f6f8fb",
    textActive: "#624de3",
    textError: "#f5483f",
    textHighEmphasis: "#181e25",
    textInfo: "#117df9",
    textLowEmphasis: "#788ba5",
    textMediumEmphasis: "#323b48",
    textOnColoredBg: "#ffffff",
    textSuccess: "#58cd52",
    textWarning: "#ff8e05",
  },
  sizes: {
    baseSpace01: "4px",
    baseSpace02: "8px",
    baseSpace03: "12px",
    baseSpace04: "16px",
    baseSpace05: "32px",
    baseSpace06: "48px",
    baseSpace07: "64px",
    baseSpace08: "80px",
    baseSpace09: "96px",
    baseSpace10: "112px",
  },
  fonts: {
    firaCodeRegular: "FiraCode-Regular",
    interBold: "Inter-Bold",
    interMedium: "Inter-Medium",
    interRegular: "Inter-Regular",
    interSemiBold: "Inter-SemiBold",
  },
  text: {
    appBodyL: {
      fontFamily: "interSemiBold",
      lineHeight: "20px",
      fontSize: 2,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appBodyM: {
      fontFamily: "interMedium",
      lineHeight: "20px",
      fontSize: 2,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appBodyS: {
      fontFamily: "interRegular",
      lineHeight: "20px",
      fontSize: 2,
      fontWeight: "normal",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appCaption: {
      fontFamily: "interRegular",
      lineHeight: "18px",
      fontSize: 0,
      fontWeight: "normal",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appCode: {
      fontFamily: "firaCodeRegular",
      lineHeight: "20px",
      fontSize: 1,
      fontWeight: "normal",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appSection: {
      fontFamily: "interMedium",
      textTransform: "uppercase",
      letterSpacing: "0.06px",
      lineHeight: "20px",
      fontSize: 0,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appSubtitle: {
      fontFamily: "interMedium",
      lineHeight: "32px",
      fontSize: 4,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appTitle1: {
      fontFamily: "interSemiBold",
      lineHeight: "40px",
      fontSize: 7,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    appTitle2: {
      fontFamily: "interSemiBold",
      lineHeight: "32px",
      fontSize: 6,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webBodyPrimaryL: {
      fontFamily: "interSemiBold",
      lineHeight: "30px",
      fontSize: 4,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webBodyPrimaryM: {
      fontFamily: "interMedium",
      lineHeight: "30px",
      fontSize: 4,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webBodyPrimaryS: {
      fontFamily: "interRegular",
      lineHeight: "30px",
      fontSize: 4,
      fontWeight: "normal",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webBodySecondaryL: {
      fontFamily: "interSemiBold",
      lineHeight: "26px",
      fontSize: 3,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webBodySecondaryM: {
      fontFamily: "interMedium",
      lineHeight: "26px",
      fontSize: 3,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webBodySecondaryS: {
      fontFamily: "interRegular",
      lineHeight: "26px",
      fontSize: 3,
      fontWeight: "normal",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webCode: {
      fontFamily: "firaCodeRegular",
      lineHeight: "20px",
      fontSize: 1,
      fontWeight: "normal",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webHeadline: {
      fontFamily: "interBold",
      lineHeight: "48px",
      fontSize: 8,
      fontWeight: "bold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webSection: {
      fontFamily: "interMedium",
      textTransform: "uppercase",
      letterSpacing: "0.06px",
      lineHeight: "20px",
      fontSize: 0,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webSubtitle: {
      fontFamily: "interMedium",
      lineHeight: "32px",
      fontSize: 5,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webTitle1: {
      fontFamily: "interSemiBold",
      lineHeight: "40px",
      fontSize: 7,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    webTitle2: {
      fontFamily: "interSemiBold",
      lineHeight: "32px",
      fontSize: 6,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
  },
};

export default theme;
