const theme = {
  fontWeights: {
    thin: 100,
    extraLight: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
    firaCodeRegular: 400,
    interMedium: 500,
    interSemiBold: 600,
  },
  sizes: {
    baseSpace1: "4px",
    baseSpace2: "8px",
    baseSpace3: "12px",
    baseSpace4: "16px",
    baseSpace5: "32px",
    baseSpace6: "48px",
    baseSpace7: "64px",
    baseSpace8: "80px",
    baseSpace9: "96px",
    baseSpace10: "112px",
  },
  fontSizes: ["0.8125rem", "0.875rem", "2rem"],
  lineHeights: { body: "20px", code: "20px", title: "40px" },
  colors: {
    colorsAccent: "#6650ef",
    colorsBlack: "#1e212b",
    colorsGreen: "#58cd52",
    colorsGrey: "#ccd5e1",
    colorsOrange: "#ff8e05",
    colorsRed: "#f5483f",
    colorsWhite: "#ffffff",
  },
  fonts: {
    firaCodeRegular: "FiraCode-Regular",
    interMedium: "Inter-Medium",
    interSemiBold: "Inter-SemiBold",
  },
  text: {
    body: {
      fontFamily: "interMedium",
      lineHeight: "20px",
      fontSize: 1,
      fontWeight: "medium",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    code: {
      fontFamily: "firaCodeRegular",
      lineHeight: "20px",
      fontSize: 0,
      fontWeight: "normal",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
    title: {
      fontFamily: "interSemiBold",
      lineHeight: "40px",
      fontSize: 2,
      fontWeight: "semiBold",
      color: "#c4c4c4",
      textAlign: "left",
      verticalAlign: "top",
    },
  },
};

export default theme;
