const theme = {
  fontWeights: {
    thin: 100,
    extraLight: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
  },
  fonts: {
    firaCodeRegular: "FiraCode-Regular",
    interBold: "Inter-Bold",
    interMedium: "Inter-Medium",
    interRegular: "Inter-Regular",
    interSemiBold: "Inter-SemiBold",
  },
  fontSizes: [
    "0.75rem",
    "0.875rem",
    "1rem",
    "1.125rem",
    "1.25rem",
    "1.375rem",
    "1.5rem",
    "1.75rem",
    "2rem",
    "2.5rem",
    "3.5rem",
  ],
  lineHeights: {
    webDesktopLabel: "20px",
    webMobileCode: "20px",
    webMobileLabel: "20px",
    webDesktopCode: "22px",
    webDesktopBody2L: "24px",
    webDesktopBody2M: "24px",
    webDesktopBody2S: "24px",
    webDesktopFootnote: "24px",
    webMobileBody1L: "24px",
    webMobileBody1M: "24px",
    webMobileBody1S: "24px",
    webMobileBody2L: "24px",
    webMobileBody2M: "24px",
    webMobileBody2S: "24px",
    webMobileFootnote: "24px",
    webMobileHeading2: "28px",
    webMobileHeading3: "28px",
    webDesktopBody1L: "32px",
    webDesktopBody1M: "32px",
    webDesktopBody1S: "32px",
    webDesktopHeading2: "32px",
    webDesktopHeading3: "32px",
    webMobileHeading1: "36px",
    webDesktopHeading1: "40px",
    webMobileDisplay1: "40px",
    webMobileDisplay2: "40px",
    webDesktopDisplay2: "48px",
    webDesktopDisplay1: "64px",
  },
  letterSpacings: {
    webDesktopDisplay1: "-1px",
    webDesktopDisplay2: "-1px",
    webMobileDisplay1: "-1px",
    webMobileDisplay2: "-1px",
    webDesktopLabel: "0.4000000059604645px",
    webMobileLabel: "0.4000000059604645px",
  },
  text: {
    webDesktopBody1L: {
      fontFamily: "interSemiBold",
      lineHeight: "32px",
      fontSize: 3,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopBody1M: {
      fontFamily: "interMedium",
      lineHeight: "32px",
      fontSize: 3,
      fontWeight: "medium",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopBody1S: {
      fontFamily: "interRegular",
      lineHeight: "32px",
      fontSize: 3,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopBody2L: {
      fontFamily: "interSemiBold",
      lineHeight: "24px",
      fontSize: 2,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopBody2M: {
      fontFamily: "interMedium",
      lineHeight: "24px",
      fontSize: 2,
      fontWeight: "medium",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopBody2S: {
      fontFamily: "interRegular",
      lineHeight: "24px",
      fontSize: 2,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopCode: {
      fontFamily: "firaCodeRegular",
      lineHeight: "22px",
      fontSize: 1,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopDisplay1: {
      fontFamily: "interBold",
      letterSpacing: "-1px",
      lineHeight: "64px",
      fontSize: 10,
      fontWeight: "bold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopDisplay2: {
      fontFamily: "interBold",
      letterSpacing: "-1px",
      lineHeight: "48px",
      fontSize: 9,
      fontWeight: "bold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopFootnote: {
      fontFamily: "interRegular",
      lineHeight: "24px",
      fontSize: 1,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopHeading1: {
      fontFamily: "interSemiBold",
      lineHeight: "40px",
      fontSize: 8,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopHeading2: {
      fontFamily: "interSemiBold",
      lineHeight: "32px",
      fontSize: 6,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopHeading3: {
      fontFamily: "interMedium",
      lineHeight: "32px",
      fontSize: 4,
      fontWeight: "medium",
      textAlign: "left",
      verticalAlign: "top",
    },
    webDesktopLabel: {
      fontFamily: "interSemiBold",
      textTransform: "uppercase",
      letterSpacing: "0.4000000059604645px",
      lineHeight: "20px",
      fontSize: 0,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileBody1L: {
      fontFamily: "interSemiBold",
      lineHeight: "24px",
      fontSize: 2,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileBody1M: {
      fontFamily: "interMedium",
      lineHeight: "24px",
      fontSize: 2,
      fontWeight: "medium",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileBody1S: {
      fontFamily: "interRegular",
      lineHeight: "24px",
      fontSize: 2,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileBody2L: {
      fontFamily: "interSemiBold",
      lineHeight: "24px",
      fontSize: 1,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileBody2M: {
      fontFamily: "interMedium",
      lineHeight: "24px",
      fontSize: 1,
      fontWeight: "medium",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileBody2S: {
      fontFamily: "interRegular",
      lineHeight: "24px",
      fontSize: 1,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileCode: {
      fontFamily: "firaCodeRegular",
      lineHeight: "20px",
      fontSize: 0,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileDisplay1: {
      fontFamily: "interBold",
      letterSpacing: "-1px",
      lineHeight: "40px",
      fontSize: 8,
      fontWeight: "bold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileDisplay2: {
      fontFamily: "interBold",
      letterSpacing: "-1px",
      lineHeight: "40px",
      fontSize: 8,
      fontWeight: "bold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileFootnote: {
      fontFamily: "interRegular",
      lineHeight: "24px",
      fontSize: 1,
      fontWeight: "normal",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileHeading1: {
      fontFamily: "interSemiBold",
      lineHeight: "36px",
      fontSize: 7,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileHeading2: {
      fontFamily: "interSemiBold",
      lineHeight: "28px",
      fontSize: 5,
      fontWeight: "semiBold",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileHeading3: {
      fontFamily: "interMedium",
      lineHeight: "28px",
      fontSize: 3,
      fontWeight: "medium",
      textAlign: "left",
      verticalAlign: "top",
    },
    webMobileLabel: {
      fontFamily: "interMedium",
      textTransform: "uppercase",
      letterSpacing: "0.4000000059604645px",
      lineHeight: "20px",
      fontSize: 0,
      fontWeight: "medium",
      textAlign: "left",
      verticalAlign: "top",
    },
  },
};

export default theme;
